@echo off
setlocal

:: Wherever possible, let generated files include a comment like
:: THIS FILE GENERATED BY MAUD
:: ${CMAKE_CURRENT_FUNCTION}() ${CMAKE_CURRENT_FUNCTION_LIST_FILE}:${CMAKE_CURRENT_FUNCTION_LIST_LINE}

:: invoke VsDevCmd.bat to load the necessary developer environment for scanning
:: (CMake should discover the exact path using the location of MSBuild.exe in CMAKE_VS_MSBUILD_COMMAND)
:: https://learn.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-170#developer_command_file_locations
::call "C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\Tools\VsDevCmd.bat"

:: Input is read from stdin or a file
if "%1"=="" (set IN='more') else (set IN=%~f1)
for /f "tokens=*" %%l in (%IN%) do (call :line "%%l")
exit

:line :: lines are "source file path;output ddi path"
  for /f "tokens=1,2 delims=;" %%s in (%1) do (call :scan "%%s" "%%t")
exit /b

:scan :: expanded from CMAKE_CXX_SCANDEP_SOURCE
  echo SCANNING %1 ==^> %2
exit /b
